# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UDSLauncherMac.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MacLauncher(object):
    def setupUi(self, MacLauncher):
        MacLauncher.setObjectName("MacLauncher")
        MacLauncher.setWindowModality(QtCore.Qt.NonModal)
        MacLauncher.resize(256, 150)
        MacLauncher.setCursor(QtGui.QCursor(QtCore.Qt.BusyCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/logo-uds-small"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MacLauncher.setWindowIcon(icon)
        MacLauncher.setWindowOpacity(1.0)
        self.centralwidget = QtWidgets.QWidget(MacLauncher)
        self.centralwidget.setAutoFillBackground(True)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_2.setSpacing(4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_3.setSpacing(4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.image = QtWidgets.QLabel(self.frame)
        self.image.setMinimumSize(QtCore.QSize(0, 24))
        self.image.setAutoFillBackground(True)
        self.image.setText("")
        self.image.setPixmap(QtGui.QPixmap(":/images/logo-uds-small"))
        self.image.setScaledContents(False)
        self.image.setAlignment(QtCore.Qt.AlignCenter)
        self.image.setObjectName("image")
        self.verticalLayout.addWidget(self.image)
        self.info = QtWidgets.QLabel(self.frame)
        self.info.setMaximumSize(QtCore.QSize(16777215, 16))
        self.info.setAlignment(QtCore.Qt.AlignCenter)
        self.info.setObjectName("info")
        self.verticalLayout.addWidget(self.info)
        spacerItem = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2.addWidget(self.frame)
        MacLauncher.setCentralWidget(self.centralwidget)

        self.retranslateUi(MacLauncher)
        QtCore.QMetaObject.connectSlotsByName(MacLauncher)

    def retranslateUi(self, MacLauncher):
        _translate = QtCore.QCoreApplication.translate
        MacLauncher.setWindowTitle(_translate("MacLauncher", "UDS Launcher"))
        self.info.setText(_translate("MacLauncher", "UDS Launcher"))
import UDSResources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MacLauncher = QtWidgets.QMainWindow()
    ui = Ui_MacLauncher()
    ui.setupUi(MacLauncher)
    MacLauncher.show()
    sys.exit(app.exec_())
