//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18034
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UdsAdmin {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UdsAdmin.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enabled.
        /// </summary>
        internal static string active {
            get {
                return ResourceManager.GetString("active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Allowed Groups.
        /// </summary>
        internal static string allowedGroups {
            get {
                return ResourceManager.GetString("allowedGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Groups allowed to access this service.
        /// </summary>
        internal static string allowedGroupsToolTip {
            get {
                return ResourceManager.GetString("allowedGroupsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The application will exit now.
        /// </summary>
        internal static string appWillTerminate {
            get {
                return ResourceManager.GetString("appWillTerminate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Assigned Services.
        /// </summary>
        internal static string assignedServices {
            get {
                return ResourceManager.GetString("assignedServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shows services of this kind currently assigned to users.
        /// </summary>
        internal static string assignedServicesToolTip {
            get {
                return ResourceManager.GetString("assignedServicesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Assign Service to user.
        /// </summary>
        internal static string assignToUser {
            get {
                return ResourceManager.GetString("assignToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Authenticators.
        /// </summary>
        internal static string authenticators {
            get {
                return ResourceManager.GetString("authenticators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The credentials provided are no longer valid.
        /// </summary>
        internal static string authFailed {
            get {
                return ResourceManager.GetString("authFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Blocked.
        /// </summary>
        internal static string blocked {
            get {
                return ResourceManager.GetString("blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cache.
        /// </summary>
        internal static string cache {
            get {
                return ResourceManager.GetString("cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The cache has been flushed.
        /// </summary>
        internal static string cacheFlushed {
            get {
                return ResourceManager.GetString("cacheFlushed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cache Level.
        /// </summary>
        internal static string cacheLevel {
            get {
                return ResourceManager.GetString("cacheLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Services currently in cache.
        /// </summary>
        internal static string cacheServicesToolTip {
            get {
                return ResourceManager.GetString("cacheServicesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Can&apos;t Connect to server. Please, check server and retry.
        /// </summary>
        internal static string cantConnect {
            get {
                return ResourceManager.GetString("cantConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This authenticator do not allows the creation of new groups at administration interface.
        /// </summary>
        internal static string cantCreateGroups {
            get {
                return ResourceManager.GetString("cantCreateGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This authenticator do not allows the creation of new users at administration interface.
        /// </summary>
        internal static string cantCreateUsers {
            get {
                return ResourceManager.GetString("cantCreateUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This authenticator do not allows the modification of users at administration interface.
        /// </summary>
        internal static string cantModifyUsers {
            get {
                return ResourceManager.GetString("cantModifyUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you really want to change current interface language?. Changes will take effect on next restart.
        /// </summary>
        internal static string changeLanguage {
            get {
                return ResourceManager.GetString("changeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check authenticator.
        /// </summary>
        internal static string checkAuthenticator {
            get {
                return ResourceManager.GetString("checkAuthenticator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check OS Manager.
        /// </summary>
        internal static string checkOSManager {
            get {
                return ResourceManager.GetString("checkOSManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check service provider.
        /// </summary>
        internal static string checkServiceProvider {
            get {
                return ResourceManager.GetString("checkServiceProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Connectivity.
        /// </summary>
        internal static string connectivity {
            get {
                return ResourceManager.GetString("connectivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        internal static string deleteItem {
            get {
                return ResourceManager.GetString("deleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deletion failed.
        /// </summary>
        internal static string deletionFailed {
            get {
                return ResourceManager.GetString("deletionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deployed Service.
        /// </summary>
        internal static string deployedService {
            get {
                return ResourceManager.GetString("deployedService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deployed Services.
        /// </summary>
        internal static string deployedServices {
            get {
                return ResourceManager.GetString("deployedServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disable.
        /// </summary>
        internal static string disable {
            get {
                return ResourceManager.GetString("disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Downloaded {0} KB of {1} KB at {2:0.00} KB/s.
        /// </summary>
        internal static string downloadInfo {
            get {
                return ResourceManager.GetString("downloadInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to download and install the new version?.
        /// </summary>
        internal static string downloadQuery {
            get {
                return ResourceManager.GetString("downloadQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Duplicated item.
        /// </summary>
        internal static string duplicatedItem {
            get {
                return ResourceManager.GetString("duplicatedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enable.
        /// </summary>
        internal static string enable {
            get {
                return ResourceManager.GetString("enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Get Error Information.
        /// </summary>
        internal static string errorInfo {
            get {
                return ResourceManager.GetString("errorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exit.
        /// </summary>
        internal static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Field &apos;{0}&apos; is required.
        /// </summary>
        internal static string fieldRequired {
            get {
                return ResourceManager.GetString("fieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The item do not exists anymore. Please, refresh gui (F5).
        /// </summary>
        internal static string findFailed {
            get {
                return ResourceManager.GetString("findFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Group.
        /// </summary>
        internal static string group {
            get {
                return ResourceManager.GetString("group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Group is not a Meta group!!!.
        /// </summary>
        internal static string groupIsNotMeta {
            get {
                return ResourceManager.GetString("groupIsNotMeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You need to select a group.
        /// </summary>
        internal static string groupRequired {
            get {
                return ResourceManager.GetString("groupRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Groups.
        /// </summary>
        internal static string groups {
            get {
                return ResourceManager.GetString("groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id.
        /// </summary>
        internal static string id {
            get {
                return ResourceManager.GetString("id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Import text file.
        /// </summary>
        internal static string import {
            get {
                return ResourceManager.GetString("import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Text Files|*.txt|All files|*.*.
        /// </summary>
        internal static string importFilter {
            get {
                return ResourceManager.GetString("importFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disabled.
        /// </summary>
        internal static string inactive {
            get {
                return ResourceManager.GetString("inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid credentials.
        /// </summary>
        internal static string invalidCredentials {
            get {
                return ResourceManager.GetString("invalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid Ip Address.
        /// </summary>
        internal static string invalidIpAddress {
            get {
                return ResourceManager.GetString("invalidIpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language.
        /// </summary>
        internal static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Legend.
        /// </summary>
        internal static string legend {
            get {
                return ResourceManager.GetString("legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manage groups for this authenticator.
        /// </summary>
        internal static string manageGroups {
            get {
                return ResourceManager.GetString("manageGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manage users for this authenticator.
        /// </summary>
        internal static string manageUsers {
            get {
                return ResourceManager.GetString("manageUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modification failed.
        /// </summary>
        internal static string modificationFailed {
            get {
                return ResourceManager.GetString("modificationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modifying.
        /// </summary>
        internal static string modifying {
            get {
                return ResourceManager.GetString("modifying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modify.
        /// </summary>
        internal static string modifyItem {
            get {
                return ResourceManager.GetString("modifyItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The field &apos;name&apos; is required.
        /// </summary>
        internal static string nameRequired {
            get {
                return ResourceManager.GetString("nameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You need to set up at least an Authenticator before using this..
        /// </summary>
        internal static string needsAuthenticators {
            get {
                return ResourceManager.GetString("needsAuthenticators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You need to set up at least an OS Manager before using this..
        /// </summary>
        internal static string needsOsManagers {
            get {
                return ResourceManager.GetString("needsOsManagers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You need to set up at least a Service before using this..
        /// </summary>
        internal static string needsServices {
            get {
                return ResourceManager.GetString("needsServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You should set up at least a transport before using this..
        /// </summary>
        internal static string needsTransports {
            get {
                return ResourceManager.GetString("needsTransports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transport not active for selected networks.
        /// </summary>
        internal static string negativeNetCheck {
            get {
                return ResourceManager.GetString("negativeNetCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Network End.
        /// </summary>
        internal static string netEnd {
            get {
                return ResourceManager.GetString("netEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Network end must be greater than network start.
        /// </summary>
        internal static string netRangeError {
            get {
                return ResourceManager.GetString("netRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Network Start.
        /// </summary>
        internal static string netStart {
            get {
                return ResourceManager.GetString("netStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Neworks.
        /// </summary>
        internal static string networks {
            get {
                return ResourceManager.GetString("networks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New.
        /// </summary>
        internal static string newItem {
            get {
                return ResourceManager.GetString("newItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New meta group.
        /// </summary>
        internal static string newMetaGroup {
            get {
                return ResourceManager.GetString("newMetaGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Service Provider.
        /// </summary>
        internal static string newServiceProvider {
            get {
                return ResourceManager.GetString("newServiceProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A new version of UDS Admin is required to communicate with server.
        /// </summary>
        internal static string newVersionRequired {
            get {
                return ResourceManager.GetString("newVersionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Occupied.
        /// </summary>
        internal static string occopied {
            get {
                return ResourceManager.GetString("occopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OS Manager.
        /// </summary>
        internal static string osManager {
            get {
                return ResourceManager.GetString("osManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OS Managers.
        /// </summary>
        internal static string osManagers {
            get {
                return ResourceManager.GetString("osManagers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Owner.
        /// </summary>
        internal static string owner {
            get {
                return ResourceManager.GetString("owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transport active for selected networks.
        /// </summary>
        internal static string positiveNetCheck {
            get {
                return ResourceManager.GetString("positiveNetCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Publication Failed.
        /// </summary>
        internal static string publicationFailed {
            get {
                return ResourceManager.GetString("publicationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Publications.
        /// </summary>
        internal static string publications {
            get {
                return ResourceManager.GetString("publications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Publications done from this deployed service.
        /// </summary>
        internal static string publicationsToolTip {
            get {
                return ResourceManager.GetString("publicationsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Publish.
        /// </summary>
        internal static string publish {
            get {
                return ResourceManager.GetString("publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generate a new publication for this service?.
        /// </summary>
        internal static string publishQuestion {
            get {
                return ResourceManager.GetString("publishQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure do you want to remove this item?.
        /// </summary>
        internal static string removeQuestion {
            get {
                return ResourceManager.GetString("removeQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Test unsuccessful.
        /// </summary>
        internal static string resultTestError {
            get {
                return ResourceManager.GetString("resultTestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Test successful.
        /// </summary>
        internal static string resultTestOk {
            get {
                return ResourceManager.GetString("resultTestOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search Group.
        /// </summary>
        internal static string searchGroup {
            get {
                return ResourceManager.GetString("searchGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search User.
        /// </summary>
        internal static string searchUser {
            get {
                return ResourceManager.GetString("searchUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select only one item to perform this operation..
        /// </summary>
        internal static string selectOnlyOne {
            get {
                return ResourceManager.GetString("selectOnlyOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Service Providers.
        /// </summary>
        internal static string serviceProviders {
            get {
                return ResourceManager.GetString("serviceProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You need to select a service.
        /// </summary>
        internal static string serviceRequired {
            get {
                return ResourceManager.GetString("serviceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Services.
        /// </summary>
        internal static string services {
            get {
                return ResourceManager.GetString("services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An small name with at most 8 chars and using A-Z,a-z,0-9 -_ chars is required.
        /// </summary>
        internal static string smallNameRequired {
            get {
                return ResourceManager.GetString("smallNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Src Host.
        /// </summary>
        internal static string sourceHost {
            get {
                return ResourceManager.GetString("sourceHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Src IP.
        /// </summary>
        internal static string sourceIp {
            get {
                return ResourceManager.GetString("sourceIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You need to specify the authenticator to be used.
        /// </summary>
        internal static string specifyAuthenticator {
            get {
                return ResourceManager.GetString("specifyAuthenticator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You need to specify the service to be used.
        /// </summary>
        internal static string specifyBaseService {
            get {
                return ResourceManager.GetString("specifyBaseService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You need to specify the OS Manager to be used.
        /// </summary>
        internal static string specifyOsManager {
            get {
                return ResourceManager.GetString("specifyOsManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Active.
        /// </summary>
        internal static string stateActive {
            get {
                return ResourceManager.GetString("stateActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Blocked.
        /// </summary>
        internal static string stateBlocked {
            get {
                return ResourceManager.GetString("stateBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Canceled.
        /// </summary>
        internal static string stateCanceled {
            get {
                return ResourceManager.GetString("stateCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Canceling.
        /// </summary>
        internal static string stateCanceling {
            get {
                return ResourceManager.GetString("stateCanceling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        internal static string stateError {
            get {
                return ResourceManager.GetString("stateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inactive.
        /// </summary>
        internal static string stateInactive {
            get {
                return ResourceManager.GetString("stateInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Launching publication.
        /// </summary>
        internal static string stateLaunching {
            get {
                return ResourceManager.GetString("stateLaunching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generating.
        /// </summary>
        internal static string statePreparing {
            get {
                return ResourceManager.GetString("statePreparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Waiting for removal.
        /// </summary>
        internal static string stateRemovable {
            get {
                return ResourceManager.GetString("stateRemovable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Removed.
        /// </summary>
        internal static string stateRemoved {
            get {
                return ResourceManager.GetString("stateRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Removing.
        /// </summary>
        internal static string stateRemoving {
            get {
                return ResourceManager.GetString("stateRemoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unknown.
        /// </summary>
        internal static string stateUnknown {
            get {
                return ResourceManager.GetString("stateUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ready.
        /// </summary>
        internal static string stateUsable {
            get {
                return ResourceManager.GetString("stateUsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Assign New Group.
        /// </summary>
        internal static string titleAssignNewGroup {
            get {
                return ResourceManager.GetString("titleAssignNewGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Assign Service.
        /// </summary>
        internal static string titleAssignService {
            get {
                return ResourceManager.GetString("titleAssignService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Authenticator.
        /// </summary>
        internal static string titleAuthenticator {
            get {
                return ResourceManager.GetString("titleAuthenticator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuration.
        /// </summary>
        internal static string titleConfiguration {
            get {
                return ResourceManager.GetString("titleConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deployed Service.
        /// </summary>
        internal static string titleDeployedService {
            get {
                return ResourceManager.GetString("titleDeployedService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Downloader.
        /// </summary>
        internal static string titleDownloader {
            get {
                return ResourceManager.GetString("titleDownloader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Group.
        /// </summary>
        internal static string titleGroup {
            get {
                return ResourceManager.GetString("titleGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login to UDS Administration.
        /// </summary>
        internal static string titleLogin {
            get {
                return ResourceManager.GetString("titleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UDS Administration Client.
        /// </summary>
        internal static string titleMain {
            get {
                return ResourceManager.GetString("titleMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Network.
        /// </summary>
        internal static string titleNetwork {
            get {
                return ResourceManager.GetString("titleNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OS Manager.
        /// </summary>
        internal static string titleOsManager {
            get {
                return ResourceManager.GetString("titleOsManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Service.
        /// </summary>
        internal static string titleService {
            get {
                return ResourceManager.GetString("titleService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Service Provider.
        /// </summary>
        internal static string titleServiceProvider {
            get {
                return ResourceManager.GetString("titleServiceProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transport.
        /// </summary>
        internal static string titleTransport {
            get {
                return ResourceManager.GetString("titleTransport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User.
        /// </summary>
        internal static string titleUser {
            get {
                return ResourceManager.GetString("titleUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User Preferences.
        /// </summary>
        internal static string titleUserPreferences {
            get {
                return ResourceManager.GetString("titleUserPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You need to select a transport.
        /// </summary>
        internal static string transportRequired {
            get {
                return ResourceManager.GetString("transportRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transports.
        /// </summary>
        internal static string transports {
            get {
                return ResourceManager.GetString("transports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User.
        /// </summary>
        internal static string user {
            get {
                return ResourceManager.GetString("user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User Preferences.
        /// </summary>
        internal static string userPreferences {
            get {
                return ResourceManager.GetString("userPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You need to select an user.
        /// </summary>
        internal static string userRequired {
            get {
                return ResourceManager.GetString("userRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Users.
        /// </summary>
        internal static string users {
            get {
                return ResourceManager.GetString("users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There are errors in the data provided.
        /// </summary>
        internal static string validationFailed {
            get {
                return ResourceManager.GetString("validationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a View.
        /// </summary>
        internal static string view {
            get {
                return ResourceManager.GetString("view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Waiting OS To Get Ready.
        /// </summary>
        internal static string waitingOsReady {
            get {
                return ResourceManager.GetString("waitingOsReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Yes.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
