//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UdsAdmin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UdsAdmin.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string active {
            get {
                return ResourceManager.GetString("active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed Groups.
        /// </summary>
        internal static string allowedGroups {
            get {
                return ResourceManager.GetString("allowedGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups allowed to access this service.
        /// </summary>
        internal static string allowedGroupsToolTip {
            get {
                return ResourceManager.GetString("allowedGroupsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application will exit now.
        /// </summary>
        internal static string appWillTerminate {
            get {
                return ResourceManager.GetString("appWillTerminate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned Services.
        /// </summary>
        internal static string assignedServices {
            get {
                return ResourceManager.GetString("assignedServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows services of this kind currently assigned to users.
        /// </summary>
        internal static string assignedServicesToolTip {
            get {
                return ResourceManager.GetString("assignedServicesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Service to user.
        /// </summary>
        internal static string assignToUser {
            get {
                return ResourceManager.GetString("assignToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticators.
        /// </summary>
        internal static string authenticators {
            get {
                return ResourceManager.GetString("authenticators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The credentials provided are no longer valid.
        /// </summary>
        internal static string authFailed {
            get {
                return ResourceManager.GetString("authFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked.
        /// </summary>
        internal static string blocked {
            get {
                return ResourceManager.GetString("blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache.
        /// </summary>
        internal static string cache {
            get {
                return ResourceManager.GetString("cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cache has been flushed.
        /// </summary>
        internal static string cacheFlushed {
            get {
                return ResourceManager.GetString("cacheFlushed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache Level.
        /// </summary>
        internal static string cacheLevel {
            get {
                return ResourceManager.GetString("cacheLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services currently in cache.
        /// </summary>
        internal static string cacheServicesToolTip {
            get {
                return ResourceManager.GetString("cacheServicesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t Connect to server. Please, check server and retry.
        /// </summary>
        internal static string cantConnect {
            get {
                return ResourceManager.GetString("cantConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This authenticator do not allows the creation of new groups at administration interface.
        /// </summary>
        internal static string cantCreateGroups {
            get {
                return ResourceManager.GetString("cantCreateGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This authenticator do not allows the creation of new users at administration interface.
        /// </summary>
        internal static string cantCreateUsers {
            get {
                return ResourceManager.GetString("cantCreateUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This authenticator do not allows the modification of users at administration interface.
        /// </summary>
        internal static string cantModifyUsers {
            get {
                return ResourceManager.GetString("cantModifyUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to change current interface language?. Changes will take effect on next restart.
        /// </summary>
        internal static string changeLanguage {
            get {
                return ResourceManager.GetString("changeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check authenticator.
        /// </summary>
        internal static string checkAuthenticator {
            get {
                return ResourceManager.GetString("checkAuthenticator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check OS Manager.
        /// </summary>
        internal static string checkOSManager {
            get {
                return ResourceManager.GetString("checkOSManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check service provider.
        /// </summary>
        internal static string checkServiceProvider {
            get {
                return ResourceManager.GetString("checkServiceProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure do you want to delete selected items?.
        /// </summary>
        internal static string confirmDelete {
            get {
                return ResourceManager.GetString("confirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connectivity.
        /// </summary>
        internal static string connectivity {
            get {
                return ResourceManager.GetString("connectivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string deleteItem {
            get {
                return ResourceManager.GetString("deleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion failed.
        /// </summary>
        internal static string deletionFailed {
            get {
                return ResourceManager.GetString("deletionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployed Service.
        /// </summary>
        internal static string deployedService {
            get {
                return ResourceManager.GetString("deployedService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployed Services.
        /// </summary>
        internal static string deployedServices {
            get {
                return ResourceManager.GetString("deployedServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        internal static string disable {
            get {
                return ResourceManager.GetString("disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded {0} KB of {1} KB at {2:0.00} KB/s.
        /// </summary>
        internal static string downloadInfo {
            get {
                return ResourceManager.GetString("downloadInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to download and install the new version?.
        /// </summary>
        internal static string downloadQuery {
            get {
                return ResourceManager.GetString("downloadQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicated item.
        /// </summary>
        internal static string duplicatedItem {
            get {
                return ResourceManager.GetString("duplicatedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        internal static string enable {
            get {
                return ResourceManager.GetString("enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Error Information.
        /// </summary>
        internal static string errorInfo {
            get {
                return ResourceManager.GetString("errorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; is required.
        /// </summary>
        internal static string fieldRequired {
            get {
                return ResourceManager.GetString("fieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item do not exists anymore. Please, refresh gui (F5).
        /// </summary>
        internal static string findFailed {
            get {
                return ResourceManager.GetString("findFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string group {
            get {
                return ResourceManager.GetString("group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group is not a Meta group!!!.
        /// </summary>
        internal static string groupIsNotMeta {
            get {
                return ResourceManager.GetString("groupIsNotMeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to select a group.
        /// </summary>
        internal static string groupRequired {
            get {
                return ResourceManager.GetString("groupRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        internal static string groups {
            get {
                return ResourceManager.GetString("groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string id {
            get {
                return ResourceManager.GetString("id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import text file.
        /// </summary>
        internal static string import {
            get {
                return ResourceManager.GetString("import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Files|*.txt|All files|*.*.
        /// </summary>
        internal static string importFilter {
            get {
                return ResourceManager.GetString("importFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string inactive {
            get {
                return ResourceManager.GetString("inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credentials.
        /// </summary>
        internal static string invalidCredentials {
            get {
                return ResourceManager.GetString("invalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Ip Address.
        /// </summary>
        internal static string invalidIpAddress {
            get {
                return ResourceManager.GetString("invalidIpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend.
        /// </summary>
        internal static string legend {
            get {
                return ResourceManager.GetString("legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage groups for this authenticator.
        /// </summary>
        internal static string manageGroups {
            get {
                return ResourceManager.GetString("manageGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage users for this authenticator.
        /// </summary>
        internal static string manageUsers {
            get {
                return ResourceManager.GetString("manageUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modification failed.
        /// </summary>
        internal static string modificationFailed {
            get {
                return ResourceManager.GetString("modificationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifying.
        /// </summary>
        internal static string modifying {
            get {
                return ResourceManager.GetString("modifying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        internal static string modifyItem {
            get {
                return ResourceManager.GetString("modifyItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;name&apos; is required.
        /// </summary>
        internal static string nameRequired {
            get {
                return ResourceManager.GetString("nameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to set up at least an Authenticator before using this..
        /// </summary>
        internal static string needsAuthenticators {
            get {
                return ResourceManager.GetString("needsAuthenticators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to set up at least an OS Manager before using this..
        /// </summary>
        internal static string needsOsManagers {
            get {
                return ResourceManager.GetString("needsOsManagers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to set up at least a Service before using this..
        /// </summary>
        internal static string needsServices {
            get {
                return ResourceManager.GetString("needsServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should set up at least a transport before using this..
        /// </summary>
        internal static string needsTransports {
            get {
                return ResourceManager.GetString("needsTransports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport not active for selected networks.
        /// </summary>
        internal static string negativeNetCheck {
            get {
                return ResourceManager.GetString("negativeNetCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network End.
        /// </summary>
        internal static string netEnd {
            get {
                return ResourceManager.GetString("netEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network end must be greater than network start.
        /// </summary>
        internal static string netRangeError {
            get {
                return ResourceManager.GetString("netRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Start.
        /// </summary>
        internal static string netStart {
            get {
                return ResourceManager.GetString("netStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neworks.
        /// </summary>
        internal static string networks {
            get {
                return ResourceManager.GetString("networks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string newItem {
            get {
                return ResourceManager.GetString("newItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New meta group.
        /// </summary>
        internal static string newMetaGroup {
            get {
                return ResourceManager.GetString("newMetaGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Service Provider.
        /// </summary>
        internal static string newServiceProvider {
            get {
                return ResourceManager.GetString("newServiceProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version of UDS Admin is required to communicate with server.
        /// </summary>
        internal static string newVersionRequired {
            get {
                return ResourceManager.GetString("newVersionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupied.
        /// </summary>
        internal static string occopied {
            get {
                return ResourceManager.GetString("occopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS Manager.
        /// </summary>
        internal static string osManager {
            get {
                return ResourceManager.GetString("osManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS Managers.
        /// </summary>
        internal static string osManagers {
            get {
                return ResourceManager.GetString("osManagers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        internal static string owner {
            get {
                return ResourceManager.GetString("owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport active for selected networks.
        /// </summary>
        internal static string positiveNetCheck {
            get {
                return ResourceManager.GetString("positiveNetCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publication Failed.
        /// </summary>
        internal static string publicationFailed {
            get {
                return ResourceManager.GetString("publicationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publications.
        /// </summary>
        internal static string publications {
            get {
                return ResourceManager.GetString("publications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publications done from this deployed service.
        /// </summary>
        internal static string publicationsToolTip {
            get {
                return ResourceManager.GetString("publicationsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        internal static string publish {
            get {
                return ResourceManager.GetString("publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate a new publication for this service?.
        /// </summary>
        internal static string publishQuestion {
            get {
                return ResourceManager.GetString("publishQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release &quot;In use&quot; state.
        /// </summary>
        internal static string releaseInUse {
            get {
                return ResourceManager.GetString("releaseInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure do you want to remove this item?.
        /// </summary>
        internal static string removeQuestion {
            get {
                return ResourceManager.GetString("removeQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test unsuccessful.
        /// </summary>
        internal static string resultTestError {
            get {
                return ResourceManager.GetString("resultTestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test successful.
        /// </summary>
        internal static string resultTestOk {
            get {
                return ResourceManager.GetString("resultTestOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Group.
        /// </summary>
        internal static string searchGroup {
            get {
                return ResourceManager.GetString("searchGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search User.
        /// </summary>
        internal static string searchUser {
            get {
                return ResourceManager.GetString("searchUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select only one item to perform this operation..
        /// </summary>
        internal static string selectOnlyOne {
            get {
                return ResourceManager.GetString("selectOnlyOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Providers.
        /// </summary>
        internal static string serviceProviders {
            get {
                return ResourceManager.GetString("serviceProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to select a service.
        /// </summary>
        internal static string serviceRequired {
            get {
                return ResourceManager.GetString("serviceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string services {
            get {
                return ResourceManager.GetString("services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force to Active.
        /// </summary>
        internal static string setActive {
            get {
                return ResourceManager.GetString("setActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulate &quot;In use&quot;.
        /// </summary>
        internal static string setInUse {
            get {
                return ResourceManager.GetString("setInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An small name with at most 8 chars and using A-Z,a-z,0-9 -_ chars is required.
        /// </summary>
        internal static string smallNameRequired {
            get {
                return ResourceManager.GetString("smallNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Src Host.
        /// </summary>
        internal static string sourceHost {
            get {
                return ResourceManager.GetString("sourceHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Src IP.
        /// </summary>
        internal static string sourceIp {
            get {
                return ResourceManager.GetString("sourceIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to specify the authenticator to be used.
        /// </summary>
        internal static string specifyAuthenticator {
            get {
                return ResourceManager.GetString("specifyAuthenticator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to specify the service to be used.
        /// </summary>
        internal static string specifyBaseService {
            get {
                return ResourceManager.GetString("specifyBaseService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to specify the OS Manager to be used.
        /// </summary>
        internal static string specifyOsManager {
            get {
                return ResourceManager.GetString("specifyOsManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string stateActive {
            get {
                return ResourceManager.GetString("stateActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked.
        /// </summary>
        internal static string stateBlocked {
            get {
                return ResourceManager.GetString("stateBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        internal static string stateCanceled {
            get {
                return ResourceManager.GetString("stateCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceling.
        /// </summary>
        internal static string stateCanceling {
            get {
                return ResourceManager.GetString("stateCanceling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string stateError {
            get {
                return ResourceManager.GetString("stateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        internal static string stateInactive {
            get {
                return ResourceManager.GetString("stateInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launching publication.
        /// </summary>
        internal static string stateLaunching {
            get {
                return ResourceManager.GetString("stateLaunching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating.
        /// </summary>
        internal static string statePreparing {
            get {
                return ResourceManager.GetString("statePreparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for removal.
        /// </summary>
        internal static string stateRemovable {
            get {
                return ResourceManager.GetString("stateRemovable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed.
        /// </summary>
        internal static string stateRemoved {
            get {
                return ResourceManager.GetString("stateRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing.
        /// </summary>
        internal static string stateRemoving {
            get {
                return ResourceManager.GetString("stateRemoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string stateUnknown {
            get {
                return ResourceManager.GetString("stateUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string stateUsable {
            get {
                return ResourceManager.GetString("stateUsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign New Group.
        /// </summary>
        internal static string titleAssignNewGroup {
            get {
                return ResourceManager.GetString("titleAssignNewGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Service.
        /// </summary>
        internal static string titleAssignService {
            get {
                return ResourceManager.GetString("titleAssignService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticator.
        /// </summary>
        internal static string titleAuthenticator {
            get {
                return ResourceManager.GetString("titleAuthenticator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string titleConfiguration {
            get {
                return ResourceManager.GetString("titleConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployed Service.
        /// </summary>
        internal static string titleDeployedService {
            get {
                return ResourceManager.GetString("titleDeployedService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloader.
        /// </summary>
        internal static string titleDownloader {
            get {
                return ResourceManager.GetString("titleDownloader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string titleGroup {
            get {
                return ResourceManager.GetString("titleGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to UDS Administration.
        /// </summary>
        internal static string titleLogin {
            get {
                return ResourceManager.GetString("titleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UDS Administration Client.
        /// </summary>
        internal static string titleMain {
            get {
                return ResourceManager.GetString("titleMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        internal static string titleNetwork {
            get {
                return ResourceManager.GetString("titleNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS Manager.
        /// </summary>
        internal static string titleOsManager {
            get {
                return ResourceManager.GetString("titleOsManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        internal static string titleService {
            get {
                return ResourceManager.GetString("titleService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Provider.
        /// </summary>
        internal static string titleServiceProvider {
            get {
                return ResourceManager.GetString("titleServiceProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport.
        /// </summary>
        internal static string titleTransport {
            get {
                return ResourceManager.GetString("titleTransport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string titleUser {
            get {
                return ResourceManager.GetString("titleUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Preferences.
        /// </summary>
        internal static string titleUserPreferences {
            get {
                return ResourceManager.GetString("titleUserPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to select a transport.
        /// </summary>
        internal static string transportRequired {
            get {
                return ResourceManager.GetString("transportRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transports.
        /// </summary>
        internal static string transports {
            get {
                return ResourceManager.GetString("transports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string user {
            get {
                return ResourceManager.GetString("user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Preferences.
        /// </summary>
        internal static string userPreferences {
            get {
                return ResourceManager.GetString("userPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to select an user.
        /// </summary>
        internal static string userRequired {
            get {
                return ResourceManager.GetString("userRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string users {
            get {
                return ResourceManager.GetString("users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are errors in the data provided.
        /// </summary>
        internal static string validationFailed {
            get {
                return ResourceManager.GetString("validationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string view {
            get {
                return ResourceManager.GetString("view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting OS To Get Ready.
        /// </summary>
        internal static string waitingOsReady {
            get {
                return ResourceManager.GetString("waitingOsReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
