#!/bin/sh
set -e
# Automatically added by dh_systemd_start/12.1.1
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop 'udsactor-unmanaged.service' >/dev/null || true
fi
# End automatically added section
