#!/bin/sh

SESMANFILE=/etc/pam.d/xrdp-sesman

. /usr/share/debconf/confmodule

set -e

case "$1" in
    purge)
    ;;
    remove)
       TMPFILE=$(mktemp /tmp/sesman.XXXXX)
       trap "rm -f $TMPFILE" 0
       grep -v uds $SESMANFILE > $TMPFILE  # Removes all UDS lines from sesman if they exists
       cp $TMPFILE $SESMANFILE
       trap "rm -f $TMPFILE" 0
    ;;
	upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#
