#!/bin/sh

. /usr/share/debconf/confmodule

set -e

case "$1" in
    configure)
        # Ensure actor is not running
        db_get udsactor/host
        host=$RET
        db_get udsactor/secure
        ssl=$RET
        if [ "$ssl" = "true" ]; then ssl=True; else ssl=False; fi 
        db_get udsactor/masterKey
        masterKey=$RET
        TMPFILE=$(mktemp /tmp/udsactor.cfg.XXXXX)
        trap "rm -f $TMPFILE" 0
        cat /etc/udsactor/udsactor.cfg | sed -e "s/server=.*/server=$server/; s/ssl=.*/ssl=$ssl/; s/timeout=.*/timeout=$timeout/" > $TMPFILE
        cp $TMPFILE /etc/udsactor/udsactor.cfg
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# Automatically added by dh_installinit
if [ -x "/etc/init.d/udsactor" ]; then
	update-rc.d udsactor defaults >/dev/null || exit $?
fi
# End automatically added section


exit 0
