#!/bin/sh -e

. /usr/share/debconf/confmodule
db_version 2.0

# This conf script is capable of backing up
db_capb backup

# Although configuration file can be modified "by hand", is not responsability of this config script
# to manage that changes (we have an user space configuration tool...)
#omsk=`umask`
#umask 0077
#if [ -f /etc/udsactor/udsactor.cfg ]; then
#  TMPFILE=$(mktemp /tmp/udsactor.cfg.XXXXX)
#  trap "rm -f $TMPFILE" 0
#  cat /etc/udsactor/udsactor.cfg | sed -e "s/\\[.*\\]//; s/ *= */=/; s/False/false/; s/True/true/" > $TMPFILE
#  . $TMPFILE
#  db_set udsactor/host $host
#  db_set udsactor/secure $ssl
#  db_set udsactor/masterKey $masterKey
#fi
#umask $omsk


STATE=1 
while [ "$STATE" != 0 -a "$STATE" != 4 ]; do
  case "$STATE" in
    1)
      db_input high udsactor/host || true
      ;;
    2)
      db_input high udsactor/secure || true
      ;;
    3)
      db_input high udsactor/masterKey || true
      ;;      
  esac

  if db_go; then
      STATE=$(($STATE + 1))
  else
      STATE=$(($STATE - 1))
  fi
    
done
