# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-10 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uds', '0021_auto_20160405_0429'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbfile',
            name='owner',
            field=models.CharField(default='', max_length=32),
        ),
    ]
