# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-15 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uds', '0021_auto_20160405_0429'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketstore',
            name='owner',
            field=models.CharField(blank=True, default=None, max_length=8, null=True),
        ),
    ]
