# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-10 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uds', '0022_dbfile_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='allowed_oss',
            field=models.CharField(default='', max_length=255),
        ),
    ]
