# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-10-25 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uds', '0023_transport_allowed_oss'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployedservice',
            name='allow_users_remove',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deployedservice',
            name='short_name',
            field=models.CharField(default='', max_length=32),
        ),
    ]
