# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-24 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uds', '0023_ticketstore_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='allowed_oss',
            field=models.CharField(default='', max_length=255),
        ),
    ]
