# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-11-29 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uds', '0024_auto_20171025_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployedservice',
            name='ignores_unused',
            field=models.BooleanField(default=False),
        ),
    ]
