# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-03-02 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uds', '0025_deployedservice_ignores_unused'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbfile',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='dbfile',
            name='modified',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='delayedtask',
            name='insert_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='last_execution',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='userservice',
            name='state_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
