# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-03-14 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uds', '0026_auto_20180302_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployedservice',
            name='allow_users_reset',
            field=models.BooleanField(default=False),
        ),
    ]
