# Generated by Django 2.2.4 on 2019-08-14 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uds', '0029_auto_20181003_1049'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeployedService',
            new_name='ServicePool',
        ),
    ]
