# Generated by Django 2.2.4 on 2019-08-14 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uds', '0030_auto_20190814_0912'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeployedServicePublication',
            new_name='ServicePoolPublication',
        ),
    ]
