# Generated by Django 2.2.4 on 2019-08-14 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uds', '0032_auto_20190814_0945'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServicesPoolGroup',
            new_name='ServicePoolGroup',
        ),
    ]
