# Generated by Django 2.2.7 on 2019-11-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uds', '0033_auto_20190814_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActorToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('ip_from', models.CharField(max_length=128)),
                ('ip', models.CharField(max_length=128)),
                ('mac', models.CharField(db_index=True, max_length=128, unique=True)),
                ('pre_command', models.CharField(blank=True, default='', max_length=255)),
                ('post_command', models.CharField(blank=True, default='', max_length=255)),
                ('runonce_command', models.CharField(blank=True, default='', max_length=255)),
                ('log_level', models.IntegerField()),
                ('token', models.CharField(db_index=True, max_length=48, unique=True)),
                ('stamp', models.DateTimeField()),
            ],
        ),
    ]
