# Generated by Django 3.0.1 on 2019-12-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uds', '0034_actortoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticator',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
