# Generated by Django 3.0.1 on 2020-01-31 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uds', '0035_authenticator_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='metapool',
            name='calendar_message',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='servicepool',
            name='calendar_message',
            field=models.CharField(default='', max_length=256),
        ),
    ]
