# Generated by Django 3.2 on 2021-04-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uds', '0039_auto_20201111_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='metapool',
            name='transport_grouping',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transport',
            name='label',
            field=models.CharField(db_index=True, default='', max_length=32),
        ),
    ]
