# Generated by Django 3.2.4 on 2021-06-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uds', '0041_auto_20210624_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='TunnelToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('ip_from', models.CharField(max_length=16)),
                ('ip', models.CharField(max_length=16)),
                ('hostname', models.CharField(max_length=128)),
                ('token', models.CharField(db_index=True, max_length=48, unique=True)),
                ('stamp', models.DateTimeField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='tunneltoken',
            constraint=models.UniqueConstraint(fields=('ip', 'hostname'), name='tt_ip_hostname'),
        ),
    ]
