# Generated by Django 3.2.8 on 2021-10-27 12:21

from django.db import migrations

# From REST API:
# Pair of section/value removed from current UDS version
REMOVED = {
    'UDS': (
        'allowPreferencesAccess',
        'customHtmlLogin',
        'UDS Theme',
        'UDS Theme Enhaced',
        'css',
        'allowPreferencesAccess',
        'loginUrl',
        'maxLoginTries',
        'loginBlockTime',
    ),
    'Cluster': ('Destination CPU Load', 'Migration CPU Load', 'Migration Free Memory'),
    'IPAUTH': ('autoLogin',),
    'VMWare': ('minUsableDatastoreGB', 'maxRetriesOnError'),
    'HyperV': ('minUsableDatastoreGB',),
    'Security': ('adminIdleTime', 'userSessionLength', 'Master Key'),
    'SAML': ('IDP Metadata cache', 'Global logout on exit')
}


def clean_config(apps, schema_editor):
    Config = apps.get_model('uds', 'Config')
    # Remove all configs that are in REMOVED
    for section, keys in REMOVED.items():
        for key in keys:
            Config.objects.filter(section=section, key=key).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('uds', '0042_auto_20210628_1533'),
    ]

    operations = [
        # 
        migrations.RunPython(clean_config, lambda apps, schema_editor: None),
    ]
