# Generated by Django 4.1 on 2022-10-01 06:23

from django.db import migrations, models
import django.db.models.deletion
import uds.core.util.model
import uds.models.notifications
import uds.models.user_service_session
import uds.models.util


class Migration(migrations.Migration):

    dependencies = [
        ("uds", "0043_auto_20220704_2120"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stamp", models.DateTimeField(auto_now_add=True)),
                ("group", models.CharField(db_index=True, max_length=128)),
                ("identificator", models.CharField(db_index=True, max_length=128)),
                ("level", models.PositiveSmallIntegerField()),
                ("message", models.TextField()),
                ("processed", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "uds_notification",
            },
        ),
        migrations.CreateModel(
            name="Notifier",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.CharField(
                        default=uds.core.util.model.generateUuid,
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("data_type", models.CharField(max_length=128)),
                ("data", models.TextField(default="")),
                ("name", models.CharField(default="", max_length=128)),
                ("comments", models.CharField(default="", max_length=256)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        default=uds.models.notifications.NotificationLevel["ERROR"]
                    ),
                ),
            ],
            options={
                "db_table": "uds_notify_prov",
            },
        ),
        migrations.CreateModel(
            name="ServiceTokenAlias",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alias", models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserServiceSession",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=uds.models.user_service_session._session_id_generator,
                        max_length=128,
                    ),
                ),
                ("start", models.DateTimeField(default=uds.models.util.getSqlDatetime)),
                ("end", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "uds__user_service_session",
            },
        ),
        migrations.DeleteModel(
            name="DBFile",
        ),
        migrations.RemoveField(
            model_name="authenticator",
            name="visible",
        ),
        migrations.RemoveField(
            model_name="service",
            name="proxy",
        ),
        migrations.RemoveField(
            model_name="transport",
            name="nets_positive",
        ),
        migrations.RemoveField(
            model_name="userservice",
            name="cluster_node",
        ),
        migrations.AddField(
            model_name="authenticator",
            name="net_filtering",
            field=models.CharField(db_index=True, default="n", max_length=1),
        ),
        migrations.AddField(
            model_name="authenticator",
            name="state",
            field=models.CharField(db_index=True, default="v", max_length=1),
        ),
        migrations.AddField(
            model_name="config",
            name="help",
            field=models.CharField(default="", max_length=256),
        ),
        migrations.AddField(
            model_name="metapool",
            name="ha_policy",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="network",
            name="authenticators",
            field=models.ManyToManyField(
                db_table="uds_net_auths",
                related_name="networks",
                to="uds.authenticator",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="max_services_count_type",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="transport",
            name="net_filtering",
            field=models.CharField(db_index=True, default="n", max_length=1),
        ),
        migrations.AlterField(
            model_name="account",
            name="comments",
            field=models.CharField(default="", max_length=256),
        ),
        migrations.AlterField(
            model_name="account",
            name="uuid",
            field=models.CharField(
                default=uds.core.util.model.generateUuid, max_length=50, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="accountusage",
            name="uuid",
            field=models.CharField(
                default=uds.core.util.model.generateUuid, max_length=50, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="authenticator",
            name="uuid",
            field=models.CharField(
                default=uds.core.util.model.generateUuid, max_length=50, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="calendar",
            name="uuid",
            field=models.CharField(
                default=uds.core.util.model.generateUuid, max_length=50, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="calendaraccess",
            name="uuid",
            field=models.CharField(
                default=uds.core.util.model.generateUuid, max_length=50, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="calendaraccessmeta",
            name="uuid",
            field=models.CharField(
                default=uds.core.util.model.generateUuid, max_length=50, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="calendaraction",
            name="uuid",
            field=models.CharField(
                default=uds.core.util.model.generateUuid, max_length=50, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="calendarrule",
            name="uuid",
            field=models.CharField(
                default=uds.core.util.model.generateUuid, max_length=50, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="uuid",
            field=models.CharField(
                default=uds.core.util.model.generateUuid, max_length=50, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="uuid",
            field=models.CharField(
                default=uds.core.util.model.generateUuid, max_length=50, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="metapool",
            name="uuid",
            field=models.CharField(
                default=uds.core.util.model.generateUuid, max_length=50, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="metapoolmember",
            name="uuid",
            field=models.CharField(
                default=uds.core.util.model.generateUuid, max_length=50, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="mfa",
            name="uuid",
            field=models.CharField(
                default=uds.core.util.model.generateUuid, max_length=50, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="network",
            name="uuid",
            field=models.CharField(
                default=uds.core.util.model.generateUuid, max_length=50, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="osmanager",
            name="uuid",
            field=models.CharField(
                default=uds.core.util.model.generateUuid, max_length=50, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="permissions",
            name="uuid",
            field=models.CharField(
                default=uds.core.util.model.generateUuid, max_length=50, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="provider",
            name="uuid",
            field=models.CharField(
                default=uds.core.util.model.generateUuid, max_length=50, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="token",
            field=models.CharField(
                blank=True, default=None, max_length=64, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="uuid",
            field=models.CharField(
                default=uds.core.util.model.generateUuid, max_length=50, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="servicepool",
            name="uuid",
            field=models.CharField(
                default=uds.core.util.model.generateUuid, max_length=50, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="servicepoolgroup",
            name="uuid",
            field=models.CharField(
                default=uds.core.util.model.generateUuid, max_length=50, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="servicepoolpublication",
            name="uuid",
            field=models.CharField(
                default=uds.core.util.model.generateUuid, max_length=50, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="uuid",
            field=models.CharField(
                default=uds.core.util.model.generateUuid, max_length=50, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="ticketstore",
            name="uuid",
            field=models.CharField(
                default=uds.core.util.model.generateUuid, max_length=50, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="transport",
            name="uuid",
            field=models.CharField(
                default=uds.core.util.model.generateUuid, max_length=50, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="tunneltoken",
            name="ip",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="tunneltoken",
            name="ip_from",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="user",
            name="uuid",
            field=models.CharField(
                default=uds.core.util.model.generateUuid, max_length=50, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="userservice",
            name="src_ip",
            field=models.CharField(default="", max_length=128),
        ),
        migrations.AlterField(
            model_name="userservice",
            name="uuid",
            field=models.CharField(
                default=uds.core.util.model.generateUuid, max_length=50, unique=True
            ),
        ),
        migrations.DeleteModel(
            name="Proxy",
        ),
        migrations.AddField(
            model_name="userservicesession",
            name="user_service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="uds.userservice",
            ),
        ),
        migrations.AddField(
            model_name="servicetokenalias",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aliases",
                to="uds.service",
            ),
        ),
        migrations.AddField(
            model_name="notifier",
            name="tags",
            field=models.ManyToManyField(to="uds.tag"),
        ),
        migrations.AddConstraint(
            model_name="userservicesession",
            constraint=models.UniqueConstraint(
                fields=("session_id", "user_service"), name="u_session_userservice"
            ),
        ),
    ]
