# Generated by Django 4.2 on 2023-04-20 03:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uds", "0044_notification_notifier_servicetokenalias_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="log",
            name="name",
            field=models.CharField(default="", max_length=64),
        ),
    ]
