# Generated by Django 4.2.1 on 2023-07-12 04:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uds", "0045_actortoken_custom_log_name"),
    ]

    operations = [
        migrations.RenameModel(
            'TunnelToken',
            'RegisteredServers',
        ),
        migrations.AddField(
            model_name="registeredservers",
            name="kind",
            field=models.IntegerField(default=1),
        ),
    ]
