# Generated by Django 5.0.1 on 2024-03-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uds", "0046_registered_server_migration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicepool",
            name="custom_message",
            field=models.CharField(default="", max_length=1024),
        ),
        migrations.AddField(
            model_name="servicepool",
            name="display_custom_message",
            field=models.BooleanField(default=False),
        ),
    ]
