# Generated by Django 5.2.5 on 2025-09-05 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uds", "0047_servicepool_custom_message_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketstore",
            name="owner",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
