# Generated by Django 5.2.6 on 2025-10-09 23:27

from django.db import migrations


def add_prefix_to_passwords(apps, schema_editor):
    Authenticator = apps.get_model('uds', 'Authenticator')
    Config = apps.get_model('uds', 'Config')

    prefix = 'old_uds_hasher$'

    for authenticator in Authenticator.objects.all():
        for user in authenticator.users.all():
            if not user.password.startswith(prefix):
                user.password = prefix + user.password
                user.save(update_fields=['password'])

    try:
        root_pass_entry = Config.objects.get(section='Security', key='rootPass')
        if not root_pass_entry.value.startswith(prefix):
            root_pass_entry.value = prefix + root_pass_entry.value
            root_pass_entry.save(update_fields=['value'])
    except Config.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('uds', '0048_alter_ticketstore_owner'),
    ]

    operations = [
        migrations.RunPython(add_prefix_to_passwords),
    ]
